### ISSUE TITLE
Search results box not oblique

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/oblique#100]
On the search results page, the page content is not shown in an oblique form like on single post page.
http://prntscr.com/gsm5ss

https://secure.helpscout.net/conversation/441466277/144343/?folderId=212385

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu when there are multiple results, the navigation buttons are interfering with the main content https://prnt.sc/iwiv09. Could you please check and see if it's possible to change it like on the single post page ? https://prnt.sc/iwivfz

**Comment by cosmin-serbanescu** [comment]
Fixed it, sorry - don't know why I had the feeling navigation was inside the container :)  and adjusted also the search form on the 404 page. I'll add these to the pro version as well.
