### ISSUE TITLE
add upgrade page to WP dashboard

### ISSUE THREAD

**Issue by dascalescuro** [Codeinwp/oblique#104]
@rodica-andronache could you please add the new upgrade page for Oblique to the WP dashboard, just like we did for Zerif etc..?

https://themeisle.com/themes/oblique-pro/upgrade

@ineagu I added the new header, so please let me know what you think: https://themeisle.com/themes/oblique-pro/

let me know if there are issues.

**Comment by rodica-andronache** [comment]
@dascalescuro done
