### ISSUE TITLE
Investigate line issue

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/oblique#107]
This seems to be happening because the svg path is not placed well, the "line" is actually the white background showing because the black path is not covering the full thing.

as mentioned here: https://github.com/Codeinwp/oblique/issues/88

A user reported this today for woocommerce products and I was able to fix it on chrome by using the following code:

.woocommerce ul.products li.product div.post-svg, .woocommerce-page ul.products li.product div.post-svg { top: 0px !important; left: -1px; width: 100%; }

.single_product_top_svg svg { left: -3px; }

Image of issue happening on Mac OS chrome: https://imgur.com/a/rgcsm

---

Thing is on my chrome(windows) it was not as severe, so based on the OS the svg path might be getting displaced more or less.

Will look closer into it

**Comment by mileamadalin** [comment]
@rodica-andronache this issue is present on safari browser as well

**Comment by HardeepAsrani** [comment]
A user has been waiting for 8 days here for the reply, so can we get an ETA for it, if possible? @rodica-andronache 

https://secure.helpscout.net/conversation/533335543/156093?folderId=212385

**Comment by rodica-andronache** [comment]
@UVLabs @mileamadalin @HardeepAsrani 
@cosmin-serbanescu tried for some time fixing all these problems on all browsers but apparently is pretty difficult to fix it. He made some changes(in the latest release) and it should be better in most browsers but there are still some lines appearing here and there. So, unless one of you wants to try it and thinks he can fix everything, I will close this for now :)
