### ISSUE TITLE
Search button on 404 not found page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/oblique#113]
https://prnt.sc/ixxaf3

Make sure it doesn't break the search buttons on other places 👍

**Comment by rodica-andronache** [comment]
Same here: can you please also have a look on the Search and Product Search widgets in the sidebar too https://prnt.sc/iyhcys ? 🌮

**Comment by rodica-andronache** [comment]
the search bar is fluctuating on mobile. Is that ok?
https://prnt.sc/izo012 - 488
https://prnt.sc/iznzto - 462
https://prnt.sc/iznz7y - 451
https://prnt.sc/iznzej - 449

**Comment by cosmin-serbanescu** [comment]
those should look fine now - fixed them on the pro version too
