### ISSUE TITLE
IMDB Logo in Social Menu

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/oblique#114]
@rodica-andronache We some customer that asks for the IMDB logo in Social Menu. Can we do that? 

https://wordpress.org/support/topic/imdb-logo-in-social-menu/

**Comment by rodica-andronache** [comment]
@mileamadalin here @cosmin-serbanescu updated font awesome https://github.com/Codeinwp/oblique/pull/112. Can you check if that icon is in there

**Comment by cosmin-serbanescu** [comment]
yes, I've added it to the social nav menu - will be adding it to the pro version too
