### ISSUE TITLE
Add Footer menu to make the theme GDPR compliant

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/oblique#121]
As per GDPR rules, All Bloggers and other Website owners have to have a privacy policy and site notes. the privacy policy HAS to be accessible within ONE CLICK from everywhere on the website.

Adding menu to the footer from Pro theme will resolve this.

Ticket: https://secure.helpscout.net/conversation/575723832/160945?folderId=1755462

@rodica-andronache

**Comment by rodica-andronache** [comment]
@Vishakha-Patel thanks 👍 could you please also make a pull request every time you are committing something so I can see it? Plus, please add a few notes in the commit message except the number of the issue you fixed, as of right now, it's really hard to access your commit. If i click on it, it redirects me to the issue itself 👍

**Comment by rodica-andronache** [comment]
@Vishakha-Patel  👍 the problem with the responsive part, was that you added the code for desktop, after the media queries

**Comment by rodica-andronache** [comment]
@Vishakha-Patel there was also a good idea to remove the callback, so that for users that update their theme, don't get by default a menu with all their site pages :)
