### ISSUE TITLE
I want to remove the text "Category: Cloud Computing"

### ISSUE THREAD

**Issue by rangesoftsolutions** [Codeinwp/oblique#14]
I have linked the Category to my menu and when i open the a Category In that page i am getting
"Category: Cloud Computing"  I just want to remove that "Category" and only " Cloud Computing" should be there .can you help me out

**Comment by rodica-andronache** [comment]
Hi,

Unfortunately this is how the theme was designed and there is no way to remove that keyword.

Regards,
Rodica
