### ISSUE TITLE
Flyfreemedia link in customizer down

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/oblique#19]
Link down: flyfreemedia.com/documentation/oblique

I realized that flyfreemedia.com simply redirects to themeisle.com. Since I am just creating the documentation for this theme, I'm opening this issue as a reminder to change the link after the documentation is published.

**Comment by rodica-andronache** [comment]
Hi @UVLabs ,

If you want, you can add a commit for this :D to replace the link with our new documentation http://docs.themeisle.com/article/294-oblique-documentation 
What do you think?

**Comment by UVLabs** [comment]
@rodica-andronache Yes I will no problem.

**Comment by UVLabs** [comment]
Fixed in #27

**Comment by rodica-andronache** [comment]
thanks :)
