### ISSUE TITLE
Header SVG not filling screen correctly

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/oblique#3]
![image](https://cloud.githubusercontent.com/assets/15010186/11366122/fbf646bc-92b3-11e5-99db-ba9e89ca90f0.png)

Doesn't happen always. Only when window is at various resolutions.

**Comment by claudiuvertistudio** [comment]
It seems to work well.

**Comment by abaicus** [comment]
We pinpointed it to the latest Chrome browser update that has solved the issue.
