### ISSUE TITLE
Post order bug

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/oblique#31]
When the front page is set to display latest post, the display order of posts is from left to right while for rest of the rows it's right to left.

**Comment by suyogyashukla** [comment]
@rodica-andronache @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@suyogyashukla What do you mean? Can you share some visual?

**Comment by rodica-andronache** [comment]
@suyogyashukla no, it's not fixed yet. I'll add in the list to be fixed/or at least investigated this week and let you know.

@HardeepAsrani he's saying that the order of the posts on homepage is something like this http://prntscr.com/ccisj3
and it should be something like this http://prntscr.com/ccit1x . In chronological order

**Comment by HardeepAsrani** [comment]
@rodica-andronache I know the fix. Will send it in minutes. :)

**Comment by rodica-andronache** [comment]
@HardeepAsrani nice job, thanks :)
