### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/oblique#41]
The theme is translating `%1$s` in the code. You can find it here: https://wordpress.org/support/topic/1s-is-mistakenly-translated-into-%ef%bc%85%ef%bc%91%ef%bc%84%ef%bd%93-in-chinese-locale?replies=8

@rodica-andronache

**Comment by rodica-andronache** [comment]
@HardeepAsrani isn't the same as here https://github.com/Codeinwp/oblique/issues/39?

**Comment by HardeepAsrani** [comment]
Yes. Couldn't find the thread when I was posting. I'll close this one.
