### ISSUE TITLE
Configure grunt

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/oblique#48]
and fix errors

We need to be careful not to change strings and text domains, to not influence the wp.org translations

**Comment by rodica-andronache** [comment]
please fix the issues here from grunt travis. I started to do this, but there are still issues

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , done. Let me know what to do with those errors from phpcs:
`
FILE: ...mp\www\wordpress\wp-content\themes\oblique\inc\template-tags.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
  86 | ERROR | Strings should have translatable content
  96 | ERROR | Strings should have translatable content
 108 | ERROR | Strings should have translatable content

----------------------------------------------------------------------
`

**Comment by rodica-andronache** [comment]
I added a rule to ignore that, for now
