### ISSUE TITLE
Posts SVG act weird at different resolutions

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/oblique#5]
![pasted image at 2015_11_25 04_19 pm](https://cloud.githubusercontent.com/assets/15010186/11399566/e905f8e4-9390-11e5-84cd-b85a9c77663e.png)

**Comment by claudiuvertistudio** [comment]
It seems to work well.

**Comment by rodica-andronache** [comment]
@abaicus is this still available? can we close it?

**Comment by rodica-andronache** [comment]
@claudiuvertistudio a user just reported this http://themeisle.com/forums/topic/strange-lines-appearing-on-macbook-pro-retina-and-iphone-6/
It seams to be an issue on Mac. Can we do anything here?

**Comment by abaicus** [comment]
@rodica-andronache That is not the same issue... this is so weird.

**Comment by claudiuvertistudio** [comment]
I don't know how to solve this issue.
