### ISSUE TITLE
Use the custom logo option from wp

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/oblique#51]
And make sure to migrate the old option, something like this possible https://github.com/Codeinwp/bookrev/blob/7b0fad078abe91556006c4da64688e00105905ff/functions.php#L313

do the same in pro

**Comment by cosmin-serbanescu** [comment]
@rodica-andronache , please let me know if everything looks good so I can add the changes to the pro version as well

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu I added a review on the PR
