### ISSUE TITLE
Customer sugestion

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/oblique#75]
@selul @rodica-andronache 

Thank you. Just that. I'm a totally unprofessional blogger (but a professional author, fiction, Italy is my country) and I'm using the Free version of your wonderful "Oblique" theme. It's fast, it's steamlined, it's just plain wonderful: exactly what I was looking for.

Want a suggestion to make the Oblique even more great? The possibility to have the most recent post full-width, and the others just like they are now. That would be GREAT.

I'm on a very strict budget, but if this situation will improve, I will seriously consider buying the Oblique Pro Version.

In the meanwhile, take my best regards.

**Comment by rodica-andronache** [comment]
@mileamadalin thanks, please just try to write the exact suggestion or bug in the issue (content and title of the issue), not the whole message :)
