### ISSUE TITLE
Add some space between gallery images

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/oblique#76]
@rodica-andronache if you add a gallery to a post with these settings: http://prntscr.com/dujhnv

They will show up stuck together on the post: http://prntscr.com/dujhv7 a user request was for adding some space between them, let me know what you think about this

**Comment by rodica-andronache** [comment]
@UVLabs I'm not sure, maybe we'll add this in the future. Until then, maybe you can help him with a custom code, as it's not something big, or as you think :)
