### ISSUE TITLE
Submenu not open on click the parent menu

### ISSUE THREAD

**Issue by poonam9** [Codeinwp/oblique#85]
@rodica-andronache When we click on a parent menu it doesn't show the submenu, it only expands when we click + plus symbol.
It should appear after the menu clicks not only on the + symbol.

**Comment by rodica-andronache** [comment]
@poonam9 I don't understand what you mean here. Can you please explain more? maybe with a small video

**Comment by poonam9** [comment]
See the below screenshot, Hope it can explain the issue.

![screen shot 2017-04-10 at 8 16 33 pm](https://cloud.githubusercontent.com/assets/7162739/24869095/bfd09c4c-1e2f-11e7-8fc3-f76ce2b2febc.png)

**Comment by rodica-andronache** [comment]
@poonam9 thanks for explaining. The thing is that is a custom link ( set to # in this case ). Clicking on it , it will take you to that URL ( # in this case ) that's why it's not opening the submenu. It's not a bug, that's how it supposed to work. That's why we have the + button
