### ISSUE TITLE
Visual issues in Safari

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/oblique#96]
When viewing a single WooCommerce product, when viewing in Safari on Mac, the page has some visual issues, as seen here: https://imgur.com/U3WgNSm

@rodica-andronache

**Comment by rodica-andronache** [comment]
@bogdanpopa90 what do you think about this? it would be easy to fix this?
https://secure.helpscout.net/conversation/427302603/142366/?folderId=212385

**Comment by bogdanpopa90** [comment]
@rodica-andronache I don't know, it may be necessary to add custom CSS for Safari users.

**Comment by HardeepAsrani** [comment]
@rodica-andronache That shouldn't be an issue, no?

**Comment by JackE9** [comment]
@HardeepAsrani @bogdanpopa90 @rodica-andronache 

Hi everyone, I am still experiencing the issues mentioned in this thread. Are there any updates or targets to fix the issues?

Thanks

**Comment by rodica-andronache** [comment]
This is also related I think https://github.com/Codeinwp/oblique/issues/88
