### ISSUE TITLE
Social menu new window

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/oblique#98]
So here: https://github.com/Codeinwp/oblique/blob/1483a0fb2169869cb633cd37f3241f5bdd084be0/js/scripts.js#L12-L15

We use JavaScript to make all the social items open in a new tab. Which makes sense, but menus already have an option to allow users to make that choice so we can just use that instead of forcing them to open in new tab.

@abaicus @rodica-andronache

**Comment by HardeepAsrani** [comment]
If it's fine for you, I can make the same changes on Pro. What say? @rodica-andronache

**Comment by rodica-andronache** [comment]
@HardeepAsrani i think it's ok. You can make the changes in pro
